# Site wide configuration

title: Louisville Old Time Squares Association
locale: en_US
description: Promoting traditional community square dance and old time music in and around Louisville, Kentucky
logo:
search: true
url: 


# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: null
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "so-simple-theme-LICENSE", "README.md", "so-simple-theme-README.md", "vendor"]

collections:
  - links


# Site owner
owner:
  name: Louisville Old Time Squares Association
  avatar: bio-photo.jpg
  email: louisvillesquares@gmail.com
  disqus-shortname:
  twitter:
  facebook: groups/LOTSA/
  github:
  stackexchange:
  linkedin:
  instagram:
  flickr:
  tumblr:
  google:
    plus:
    analytics:
    verify:
    ad-client:
    ad-slot: 
  bing-verify: